[package]
name = "qctimer_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.86", features = ["full"] }
quote = "1.0"
chrono = "0.4.38"
futures = "0.3.30"
